name: www.bana.rs
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
defaults:
  run:
    shell: bash
env:
  TERM: "xterm-256color"
jobs:
  www:
    continue-on-error: true
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-20.04
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: environment-details
        continue-on-error: true
        shell: bash
        run: |
          pwd
          uname -a

      - name: install-dependencies
        run: |
          sudo apt install curl
          curl -o zola.tar.gz -L "https://github.com/getzola/zola/releases/download/v0.18.0/zola-v0.18.0-x86_64-unknown-linux-gnu.tar.gz"
          sudo tar -xvf zola.tar.gz -C /usr/bin
          zola --version

      - name: build
        run: |
          zola check
